### ISSUE TITLE
details of sequence uniqueness file?

### ISSUE THREAD

**Issue by daskelly** [COMBINE-lab/minnow#11]
Hello, would it be possible to provide more details on how to construct the sequence uniqueness file? (i.e. the file passed to --uniq). 

I found this file at your Zenodo link for the human genome, but I'd like to make my own for the mouse genome. And ideally it would be great to know how to construct it so I could apply this to other genomes. 

Thanks!

**Comment by hiraksarkar** [comment]
Hi @daskelly , 

Thanks for trying minnow, Firstly, please _don't_ use the conda version since it is outdated, use https://github.com/COMBINE-lab/minnow/tree/minnow-velocity this branch for latest result, we are going to merge this branch to master very soon. 

The uniqueness file can be constructed by calculating the number of unique k-mers per gene (second column), and total number of k-mers in the third column.

**Comment by daskelly** [comment]
Thanks @hiraksarkar I will be sure to use the branch you mentioned.

Can you clarify two things about the uniqueness file:
1) When looking for k-mers what is the value of K to use?
2) How do you calculate this at the _gene_ level? Is this looking at the longest isoform?

**Comment by hiraksarkar** [comment]
Hi @daskelly ,

I used 101 as the k-mer size, as the read length default is 100. I added the script here https://github.com/COMBINE-lab/minnow/blob/minnow-velocity/scripts/frac_unique.py, Let me know if you face any bugs. I am actively working on the branch so there might be issues, and I would love to fix them if there is something I missed.

**Comment by daskelly** [comment]
Thank you @hiraksarkar, I am working through the script you provided but I think this should be enough to clarify my questions. Much appreciated!

**Comment by hiraksarkar** [comment]
No worries @daskelly , feel free to reopen, get in touch if I can be of any help.
