### ISSUE TITLE
--ReadLength in minnow simulate

### ISSUE THREAD

**Issue by hoyu310** [COMBINE-lab/minnow#19]
Does this parameter work? I tried not specifying it as well as setting --ReadLength 151, but in both cases the resulting read lengths in the R2 fastq were 100 bp. Step 1.1 (minnow index) was run with -k 151. I want the reads to be this length because it seems more realistic for 10x datasets. Your help is much appreciated.

**Comment by hiraksarkar** [comment]
Hi @hoyu310 ,

Thanks for pointing this out. At the time of development 10x used ~100 basepair reads, so we followed that. I need to change the code a bit to accommodate 150. I would definitely make the changes when I get a chance.

**Comment by hiraksarkar** [comment]
Hi @hoyu310 ,

I have added the custom read length support https://github.com/COMBINE-lab/minnow/tree/custom-read-length in this commit 378eaad7072c308c25c8eab3015f6124d7f400d0 ,  pull this branch and let me know if it works, after that I will pull that to the main branch. 

One suggestion, if you want a read length of `151` then please generate the index deBruijn graph with `153` size k-mers since the overlap required for 151 sequences are 152, but we need odd length k-mer to build the graph so index should be built with `153`, after that running with `--ReadLength 151` should work.

Thanks.

**Comment by hiraksarkar** [comment]
@hoyu310  any update ?

**Comment by hoyu310** [comment]
Thanks a lot @hiraksarkar, I'll see if it works and get back to you

**Comment by hoyu310** [comment]
I started from the step of index deBruijn graph with k = 153, and then made a quick run with 20 cells (~54,000 genes); the log at the end says 'Successfully written simulated reads'. The read lengths in the R2 fastq are 151 bp. It looks like it worked! Thanks!

**Comment by hiraksarkar** [comment]
Awesome as this is working I will merge the branch and close the issue, tagging @DongzeHE to the discussion as he might be interested in the pull request.
