### ISSUE TITLE
Changing the length of transcript read

### ISSUE THREAD

**Issue by NemanjaVucic90** [COMBINE-lab/minnow#3]
Hello, 
While following the typical example (minimal) to simulate scRNA-seq reads using alevin-mode I've encountered several obstacles:

**Comment by hiraksarkar** [comment]
Hi @NemanjaVucic90 , 

Thanks for trying out minnow. It would be great if you use the develop branch of minnow directly from github rather than conda. (in case you are not using it directly). The bioconda does not allow the prerelease packages any more, so I need to prepare a release package now. I will push it shortly.

Until then please let me know the problem you are facing.

**Comment by hiraksarkar** [comment]
Hi @NemanjaVucic90 , 

Please feel free to reopen with whatever problem you are facing.
